name = "newcritter"
main = "worker.js"
compatibility_date = "2026-09-20"

[assets]
directory = "."
binding = "ASSETS"

[triggers]
crons = ["5 0 * * 1"] # weekly reward computation, 00:05 UTC every Monday

[[d1_databases]]
binding = "DB"
database_name = "compass-critters-leaderboard"
database_id = "6c8ed1a4-1055-47a9-aaa3-3d3204ca1928"
